### PR TITLE
update test descriptor and test descriptor schema

### PR DESCRIPTION
**Pull request by andreoug**
issue #102

### CODE REVIEW

**Comment by mpeuster** [comment]
Ok, seems to work now, right? If you want, I can merge.

**Review by mpeuster — APPROVED** [review]
Btw. any reason to keep two versions of the schemas? The old ones and the new ones with `-draft` in the name? I think we can even remove the old ones, right?

**Comment by andreoug** [comment]
As far as I know we won't need the old ones.

**Comment by mpeuster** [comment]
Ok, can you remove them in your PR?

**Comment by andreoug** [comment]
I have pushed the update with 

> Btw. any reason to keep two versions of the schemas? The old ones and the new ones with `-draft` in the name? I think we can even remove the old ones, right?

I have updated it and waiting for the green signals. after that can you plz merge

**Comment by mpeuster** [comment]
All green -> merged.

**Pull request merged**
